In [1]:
from pathlib import Path
from zipfile import ZipFile

# Locate the project folder
project_folder = Path(
    r"C:\Users\jaing\Desktop\Gaurav\Coding\Python\NYC Bike Intelligence"
)

# Find ZIP files in the raw data folder
raw_folder = project_folder / "data" / "raw"
zip_files = list(raw_folder.glob("*.zip"))

print("ZIP files found:", len(zip_files))

for file in zip_files:
    print(file.name)

ZIP files found: 1
202401-citibike-tripdata.zip

In [2]:
zip_path = zip_files[0]

with ZipFile(zip_path, "r") as archive:
    for item in archive.infolist():
        print(
            "Filename:", item.filename,
            "| Size (MB):", round(item.file_size / (1024 ** 2), 2)
        )

Filename: 202401-citibike-tripdata_2.csv | Size (MB): 165.62
Filename: 202401-citibike-tripdata_1.csv | Size (MB): 186.32

In [3]:
import pandas as pd

with ZipFile(zip_path, "r") as archive:
    for filename in archive.namelist():
        if filename.endswith(".csv"):
            print(f"\n--- {filename} ---")

            sample = pd.read_csv(
                archive.open(filename),
                nrows=5
            )

            print("Columns:")
            print(sample.columns.tolist())

            display(sample)

--- 202401-citibike-tripdata_2.csv ---
Columns:
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual']

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,62EF1AC5BE598131,classic_bike,2024-01-24 09:03:33.533,2024-01-24 09:06:53.535,E 102 St & 1 Ave,7407.13,E 103 St & Lexington Ave,7463.09,40.786995,-73.941648,40.790305,-73.947558,member
1,8464E543DAB27DBF,classic_bike,2024-01-30 08:21:29.510,2024-01-30 08:29:03.304,E 102 St & 1 Ave,7407.13,E 91 St & 2 Ave,7286.01,40.786995,-73.941648,40.781153,-73.949630,member
2,9C04FDC8549F5205,electric_bike,2024-01-22 21:18:25.199,2024-01-22 21:26:24.647,W 35 St & 8 Ave,6526.01,1 Ave & E 39 St,6303.01,40.752762,-73.992805,40.747140,-73.971130,member
3,7DD1703A3E0D8833,electric_bike,2024-01-31 22:15:49.861,2024-01-31 22:22:45.520,Warren St & Roosevelt Ave,6346.07,112 St & Northern Blvd,6683.01,40.749190,-73.870540,40.757880,-73.857630,member
4,6A96FCD170996E59,classic_bike,2024-01-29 22:52:28.276,2024-01-29 22:57:05.099,6 Ave & W 33 St,6364.07,W 29 St & 9 Ave,6416.06,40.749013,-73.988484,40.750073,-73.998393,member

--- 202401-citibike-tripdata_1.csv ---
Columns:
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual']

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8E865410DBDE0CA9,electric_bike,2024-01-01 13:00:04.563,2024-01-01 13:04:04.652,3 St & 3 Ave,4028.03,Carroll St & Smith St,4225.14,40.675070,-73.987752,40.680611,-73.994758,casual
1,0403D0B3FC9CA77D,electric_bike,2024-01-08 19:36:43.520,2024-01-08 19:53:16.266,Franklin Ave & St Marks Ave,4107.05,Bedford Ave & Bergen St,4066.15,40.675832,-73.956168,40.676368,-73.952918,casual
2,F6DE7BB42FF550BE,electric_bike,2024-01-12 15:00:41.580,2024-01-12 15:36:29.622,W 67 St & Broadway,7116.04,Central Park W & W 103 St,7577.27,40.774925,-73.982666,40.795590,-73.961884,casual
3,84A995BFD98030D4,classic_bike,2024-01-12 16:52:19.025,2024-01-12 17:17:29.773,Central Park West & W 68 St,7079.06,E 5 St & Ave C,5545.04,40.773407,-73.977825,40.722992,-73.979955,member
4,7BBEAD4F2B535813,electric_bike,2024-01-05 19:50:19.202,2024-01-05 20:34:42.517,W 67 St & Broadway,7116.04,Ave A & E 14 St,5779.11,40.774925,-73.982666,40.730311,-73.980472,member

In [4]:
with ZipFile(zip_path, "r") as archive:
    csv_files = [
        name for name in archive.namelist()
        if name.endswith(".csv")
    ]

    for filename in csv_files:
        sample = pd.read_csv(archive.open(filename), nrows=1000)

        print(f"\n--- {filename} ---")
        print(sample.dtypes)
        print("\nMissing values:")
        print(sample.isna().sum())

--- 202401-citibike-tripdata_2.csv ---
ride_id                   str
rideable_type             str
started_at                str
ended_at                  str
start_station_name        str
start_station_id      float64
end_station_name          str
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual             str
dtype: object

Missing values:
ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    2
start_station_id      2
end_station_name      0
end_station_id        0
start_lat             2
start_lng             2
end_lat               0
end_lng               0
member_casual         0
dtype: int64

--- 202401-citibike-tripdata_1.csv ---
ride_id                   str
rideable_type             str
started_at                str
ended_at                  str
start_station_name        str
start_station_id      float64
end_station_name          str
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual             str
dtype: object

Missing values:
ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [5]:
import pandas as pd
from zipfile import ZipFile

with ZipFile(zip_path, "r") as archive:
    csv_files = sorted(
        name for name in archive.namelist()
        if name.endswith(".csv")
    )

    dataframes = [
        pd.read_csv(archive.open(filename))
        for filename in csv_files
    ]

df = pd.concat(dataframes, ignore_index=True)

print("Total rows:", len(df))
print("Total columns:", len(df.columns))
print("\nMissing values per column:")
print(df.isna().sum())
print("\nDuplicate ride IDs:", df["ride_id"].duplicated().sum())
print("\nRider types:")
print(df["member_casual"].value_counts())

C:\Users\jaing\AppData\Local\Temp\ipykernel_13164\348283793.py:11: DtypeWarning: Columns (5: start_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(archive.open(filename))
C:\Users\jaing\AppData\Local\Temp\ipykernel_13164\348283793.py:11: DtypeWarning: Columns (5: start_station_id, 7: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(archive.open(filename))

Total rows: 1888085
Total columns: 13

Missing values per column:
ride_id                  0
rideable_type            0
started_at               0
ended_at                 0
start_station_name    1160
start_station_id      1160
end_station_name      5505
end_station_id        5505
start_lat             1160
start_lng             1160
end_lat               5486
end_lng               5486
member_casual            0
dtype: int64

Duplicate ride IDs: 0

Rider types:
member_casual
member    1679836
casual     208249
Name: count, dtype: int64

In [6]:
# Inspect the station ID columns
for col in ["start_station_id", "end_station_id"]:
    print(f"\n--- {col} ---")
    print("Data type:", df[col].dtype)
    print("Examples of non-null values:")
    print(df[col].dropna().astype(str).unique()[:15])

--- start_station_id ---
Data type: object
Examples of non-null values:
<ArrowStringArray>
['4028.03', '4107.05', '7116.04', '7079.06', '4307.13', '6218.04',  '3834.1',
 '6756.01', '5445.02', '7541.01', '4354.07', '5379.09', '6422.09', '5288.12',
 '6382.05']
Length: 15, dtype: str

--- end_station_id ---
Data type: object
Examples of non-null values:
<ArrowStringArray>
['4225.14', '4066.15', '7577.27', '5545.04', '5779.11', '6319.03', '4470.09',
 '6644.08', '5545.01', '6676.02', '5433.03', '5746.14', '5561.06', '5500.02',
 '5880.02']
Length: 15, dtype: str

In [7]:
with ZipFile(zip_path, "r") as archive:
    csv_files = sorted(
        name for name in archive.namelist()
        if name.endswith(".csv")
    )

    dataframes = [
        pd.read_csv(
            archive.open(filename),
            dtype={
                "start_station_id": "string",
                "end_station_id": "string",
            },
        )
        for filename in csv_files
    ]

df = pd.concat(dataframes, ignore_index=True)

print("Total rows:", len(df))
print("Start station ID type:", df["start_station_id"].dtype)
print("End station ID type:", df["end_station_id"].dtype)
print("Duplicate ride IDs:", df["ride_id"].duplicated().sum())

Total rows: 1888085
Start station ID type: string
End station ID type: string
Duplicate ride IDs: 0

In [8]:
# Convert timestamps to proper datetime types
df["started_at"] = pd.to_datetime(df["started_at"], errors="coerce")
df["ended_at"] = pd.to_datetime(df["ended_at"], errors="coerce")

# Calculate trip duration in minutes
df["duration_min"] = (
    df["ended_at"] - df["started_at"]
).dt.total_seconds() / 60

# Summarize timestamp quality
print("Invalid start timestamps:", df["started_at"].isna().sum())
print("Invalid end timestamps:", df["ended_at"].isna().sum())
print("Trips ending before they start:", (df["duration_min"] < 0).sum())
print("Zero-duration trips:", (df["duration_min"] == 0).sum())

print("\nTrip duration summary (minutes):")
print(df["duration_min"].describe())

Invalid start timestamps: 0
Invalid end timestamps: 0
Trips ending before they start: 0
Zero-duration trips: 0

Trip duration summary (minutes):
count    1.888085e+06
mean     1.151595e+01
std      3.379060e+01
min      1.000733e+00
25%      4.668800e+00
50%      7.742150e+00
75%      1.300192e+01
max      1.500492e+03
Name: duration_min, dtype: float64

In [9]:
# Count trips exceeding selected duration thresholds
thresholds = [30, 60, 180, 720, 1440]

for minutes in thresholds:
    count = (df["duration_min"] > minutes).sum()
    percentage = count / len(df) * 100

    print(
        f"Trips over {minutes:4} minutes: "
        f"{count:>7,} ({percentage:.3f}%)"
    )

# Inspect the 10 longest trips
longest_trips = (
    df.nlargest(10, "duration_min")[
        [
            "ride_id",
            "started_at",
            "ended_at",
            "duration_min",
            "member_casual",
            "rideable_type",
        ]
    ]
)

display(longest_trips)

Trips over   30 minutes:  79,905 (4.232%)
Trips over   60 minutes:  14,196 (0.752%)
Trips over  180 minutes:   2,422 (0.128%)
Trips over  720 minutes:   1,024 (0.054%)
Trips over 1440 minutes:     607 (0.032%)

,ride_id,started_at,ended_at,duration_min,member_casual,rideable_type
1143130,23B12F2A3BF35940,2024-01-27 12:48:55.980,2024-01-28 13:49:25.511,1500.492183,casual,classic_bike
737509,F6D18FF919362E35,2024-01-10 20:24:09.463,2024-01-11 21:24:38.205,1500.479033,casual,electric_bike
735124,540F8E89D55E2DD0,2023-12-31 15:11:49.393,2024-01-01 16:12:05.247,1500.264233,member,electric_bike
1146683,88B347481CF3E2D8,2024-01-18 16:28:47.225,2024-01-19 17:28:44.489,1499.954400,member,classic_bike
740515,D2E44592179FE476,2024-01-13 08:00:51.478,2024-01-14 09:00:48.681,1499.953383,member,classic_bike
439136,4E268A4E3995D4CC,2024-01-03 15:31:09.549,2024-01-04 16:31:06.612,1499.951050,member,classic_bike
1142794,CCC6E8095797D43F,2024-01-23 19:04:24.572,2024-01-24 20:04:21.444,1499.947867,member,electric_bike
1147942,3E030018101761A1,2024-01-29 17:30:37.847,2024-01-30 18:30:34.688,1499.947350,member,classic_bike
439308,297102DB4979BFF3,2024-01-06 20:12:42.692,2024-01-07 21:12:39.474,1499.946367,member,classic_bike
736250,500943061A4E0C9F,2024-01-08 17:26:30.206,2024-01-09 18:26:26.988,1499.946367,casual,classic_bike

## EXAMINING THE LONGER TRIPS

In [10]:
# Examine trips lasting between 24 and 26 hours
long_trips = df[
    df["duration_min"].between(1440, 1560)
].copy()

print("Trips lasting 24–26 hours:", len(long_trips))

print("\nDuration statistics:")
print(long_trips["duration_min"].describe())

print("\nRider type:")
print(long_trips["member_casual"].value_counts())

print("\nBike type:")
print(long_trips["rideable_type"].value_counts())

print("\nTrips by start date:")
print(long_trips["started_at"].dt.date.value_counts().sort_index().head(15))

Trips lasting 24–26 hours: 607

Duration statistics:
count     607.000000
mean     1498.597559
std         6.898033
min      1440.385817
25%      1499.735333
50%      1499.869833
75%      1499.904875
max      1500.492183
Name: duration_min, dtype: float64

Rider type:
member_casual
member    374
casual    233
Name: count, dtype: int64

Bike type:
rideable_type
classic_bike     520
electric_bike     87
Name: count, dtype: int64

Trips by start date:
started_at
2023-12-31    36
2024-01-01    39
2024-01-02    29
2024-01-03    25
2024-01-04    23
2024-01-05    25
2024-01-06    21
2024-01-07     8
2024-01-08    34
2024-01-09    20
2024-01-10    28
2024-01-11    21
2024-01-12    22
2024-01-13    32
2024-01-14    11
Name: count, dtype: int64

In [11]:
# Examine the most common durations among trips over 12 hours
long_trips = df[df["duration_min"] > 720].copy()

long_trips["duration_rounded"] = (
    long_trips["duration_min"].round(0).astype(int)
)

print("Trips over 12 hours:", len(long_trips))

print("\nMost common rounded durations (minutes):")
print(
    long_trips["duration_rounded"]
    .value_counts()
    .head(15)
)

print("\nCounts by duration range:")
bins = [720, 1000, 1200, 1400, 1440, 1500, 1560]
labels = [
    "12–16.7 hours",
    "16.7–20 hours",
    "20–23.3 hours",
    "23.3–24 hours",
    "24–25 hours",
    "25–26 hours",
]

print(
    pd.cut(
        long_trips["duration_min"],
        bins=bins,
        labels=labels,
        right=False,
    ).value_counts().sort_index()
)

Trips over 12 hours: 1024

Most common rounded durations (minutes):
duration_rounded
1500    581
836       5
940       4
733       4
984       3
946       3
978       3
788       3
1006      3
856       3
1032      3
779       3
806       3
720       3
721       3
Name: count, dtype: int64

Counts by duration range:
duration_min
12–16.7 hours    228
16.7–20 hours    102
20–23.3 hours     69
23.3–24 hours     18
24–25 hours      604
25–26 hours        3
Name: count, dtype: int64

In [12]:
# Inspect trips lasting approximately 25 hours
near_25_hours = df[
    df["duration_min"].between(1499, 1501)
].copy()

print("Trips lasting approximately 25 hours:", len(near_25_hours))

display(
    near_25_hours[
        [
            "ride_id",
            "started_at",
            "ended_at",
            "duration_min",
            "rideable_type",
            "member_casual",
        ]
    ].head(15)
)

Trips lasting approximately 25 hours: 582

,ride_id,started_at,ended_at,duration_min,rideable_type,member_casual
437209,1C4E7E4930D1B152,2024-01-08 23:05:49.493,2024-01-10 00:05:39.234,1499.829017,classic_bike,casual
437230,03DF018B20ED02D9,2024-01-13 14:51:04.773,2024-01-14 15:50:59.897,1499.918733,classic_bike,casual
437292,76D46614E14F6C5A,2024-01-06 01:32:01.200,2024-01-07 02:31:53.197,1499.866617,classic_bike,member
437374,45679051899B5410,2024-01-07 18:13:27.349,2024-01-08 19:13:14.714,1499.789417,classic_bike,casual
437382,E56BC488A140600F,2024-01-10 05:23:24.431,2024-01-11 06:23:18.779,1499.905800,classic_bike,member
437403,7D6A4C829F90B402,2024-01-14 10:45:41.078,2024-01-15 11:45:30.912,1499.830567,classic_bike,casual
437418,1EAAC25781AACCEE,2024-01-11 17:41:09.415,2024-01-12 18:41:03.543,1499.902133,classic_bike,member
437445,E196CB2869E257A0,2024-01-10 17:02:07.033,2024-01-11 18:01:47.463,1499.673833,classic_bike,member
437448,B8DEDB32CB8B0BD6,2024-01-06 00:55:22.611,2024-01-07 01:55:16.491,1499.898000,classic_bike,casual
437468,9A5B84825A8769D1,2024-01-05 22:22:38.160,2024-01-06 23:22:28.926,1499.846100,classic_bike,member
437641,BA8BA4BE6EE1BE1D,2024-01-10 15:40:12.279,2024-01-11 16:40:02.090,1499.830183,classic_bike,casual
437700,C1EF06112FEA1846,2024-01-01 11:46:34.010,2024-01-02 12:46:28.843,1499.913883,classic_bike,member
437701,284BB949FD60D235,2024-01-12 09:42:49.314,2024-01-13 10:42:44.751,1499.923950,classic_bike,member
437743,17C1620CC7E8B5A4,2024-01-10 07:26:45.850,2024-01-11 08:26:40.134,1499.904733,classic_bike,member
437795,8DE220098765E762,2024-01-12 17:13:06.190,2024-01-13 18:12:43.261,1499.617850,classic_bike,casual

In [13]:
# Compare the suspicious trips against exactly 25 hours
near_25_hours["difference_from_25h_min"] = (
    near_25_hours["duration_min"] - (25 * 60)
)

print("Difference from exactly 25 hours (minutes):")
display(
    near_25_hours["difference_from_25h_min"].describe()
)

print("\nTrips within 1 minute of exactly 25 hours:")
print(
    near_25_hours["difference_from_25h_min"]
    .abs()
    .le(1)
    .sum()
)

Difference from exactly 25 hours (minutes):

count    582.000000
mean      -0.167258
std        0.113660
min       -0.898500
25%       -0.217292
50%       -0.122267
75%       -0.093708
max        0.492183
Name: difference_from_25h_min, dtype: float64

Trips within 1 minute of exactly 25 hours:
582

In [14]:
# Count approximately 25-hour trips by bike type and rider type
near_25_hours.pivot_table(
    index="rideable_type",
    columns="member_casual",
    values="ride_id",
    aggfunc="count",
    fill_value=0,
    observed=False
)

member_casual  casual  member
rideable_type
classic_bike      185     313
electric_bike      43      41

In [15]:
# Flag unusual durations without deleting any records

df["duration_flag"] = "Normal"

df.loc[
    df["duration_min"] > 180,
    "duration_flag"
] = "Long: over 3 hours"

df.loc[
    df["duration_min"] > 720,
    "duration_flag"
] = "Very long: over 12 hours"

df.loc[
    df["duration_min"] >= 1440,
    "duration_flag"
] = "Investigate: 24+ hours"

# Summarize the flags
print(df["duration_flag"].value_counts())

print(
    "\nPercentage of all trips in each category:"
)

print(
    (df["duration_flag"].value_counts(normalize=True) * 100)
    .round(3)
)

duration_flag
Normal                      1885663
Long: over 3 hours             1398
Investigate: 24+ hours          607
Very long: over 12 hours        417
Name: count, dtype: int64

Percentage of all trips in each category:
duration_flag
Normal                      99.872
Long: over 3 hours           0.074
Investigate: 24+ hours       0.032
Very long: over 12 hours     0.022
Name: proportion, dtype: float64

In [16]:
# Keep 24+ hour journeys separate for later investigation
df_24h_plus = df[df["duration_min"] >= 1440].copy()

# Main dataset: exclude 24+ hour journeys
df_main = df[df["duration_min"] < 1440].copy()

print("Original dataset:", len(df))
print("Main analysis dataset:", len(df_main))
print("Set aside for investigation:", len(df_24h_plus))

print(
    "\nRows accounted for:",
    len(df_main) + len(df_24h_plus) == len(df)
)

Original dataset: 1888085
Main analysis dataset: 1887478
Set aside for investigation: 607

Rows accounted for: True

## ANALYZING MISSING DATA

In [17]:
# Check missing values in the main analysis dataset
missing = df_main.isna().sum()

missing_summary = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": (missing / len(df_main) * 100).round(3)
})

display(
    missing_summary[missing_summary["missing_count"] > 0]
    .sort_values("missing_count", ascending=False)
)

                    missing_count  missing_percent
end_station_id               4924            0.261
end_station_name             4924            0.261
end_lat                      4924            0.261
end_lng                      4924            0.261
start_station_name           1160            0.061
start_station_id             1160            0.061
start_lng                    1160            0.061
start_lat                    1160            0.061

In [18]:
# Check whether missing station fields occur together
station_missing = pd.Series({
    "Missing start station name": df_main["start_station_name"].isna().sum(),
    "Missing start station ID": df_main["start_station_id"].isna().sum(),
    "Missing either start station name or ID": (
        df_main["start_station_name"].isna()
        | df_main["start_station_id"].isna()
    ).sum(),
    "Missing end station name": df_main["end_station_name"].isna().sum(),
    "Missing end station ID": df_main["end_station_id"].isna().sum(),
    "Missing either end station name or ID": (
        df_main["end_station_name"].isna()
        | df_main["end_station_id"].isna()
    ).sum(),
})

display(station_missing.to_frame("trip_count"))

                                         trip_count
Missing start station name                     1160
Missing start station ID                       1160
Missing either start station name or ID        1160
Missing end station name                       4924
Missing end station ID                         4924
Missing either end station name or ID          4924

In [19]:
# Identify trips with missing station names
missing_start = df_main["start_station_name"].isna()
missing_end = df_main["end_station_name"].isna()

# Count each combination
overlap_summary = pd.Series({
    "Both start and end missing": (missing_start & missing_end).sum(),
    "Only start missing": (missing_start & ~missing_end).sum(),
    "Only end missing": (~missing_start & missing_end).sum(),
    "Neither missing": (~missing_start & ~missing_end).sum(),
})

display(overlap_summary.to_frame("trip_count"))

print("\nTotal trips checked:", len(df_main))
print("Counts add up correctly:", overlap_summary.sum() == len(df_main))

                            trip_count
Both start and end missing         557
Only start missing                 603
Only end missing                  4367
Neither missing                1881951

Total trips checked: 1887478
Counts add up correctly: True

In [20]:
# Check whether missing station names align with missing coordinates
coordinate_missing_summary = pd.Series({
    "Start name and coordinates all missing": (
        df_main["start_station_name"].isna()
        & df_main["start_lat"].isna()
        & df_main["start_lng"].isna()
    ).sum(),

    "End name and coordinates all missing": (
        df_main["end_station_name"].isna()
        & df_main["end_lat"].isna()
        & df_main["end_lng"].isna()
    ).sum(),

    "Start station missing but coordinates present": (
        df_main["start_station_name"].isna()
        & df_main["start_lat"].notna()
        & df_main["start_lng"].notna()
    ).sum(),

    "End station missing but coordinates present": (
        df_main["end_station_name"].isna()
        & df_main["end_lat"].notna()
        & df_main["end_lng"].notna()
    ).sum(),
})

display(coordinate_missing_summary.to_frame("trip_count"))

                                               trip_count
Start name and coordinates all missing               1160
End name and coordinates all missing                 4924
Start station missing but coordinates present           0
End station missing but coordinates present             0

In [21]:
# Flag trips with missing station information
df_main["missing_start_station"] = (
    df_main["start_station_name"].isna()
)

df_main["missing_end_station"] = (
    df_main["end_station_name"].isna()
)

# Verify the flags
print("Missing start station:", df_main["missing_start_station"].sum())
print("Missing end station:", df_main["missing_end_station"].sum())

print("\nUpdated dataset shape:", df_main.shape)

Missing start station: 1160
Missing end station: 4924

Updated dataset shape: (1887478, 17)

## Checking For Station Names & IDs Concistency

In [22]:
# Combine start and end station information
start_stations = df_main[
    ["start_station_id", "start_station_name"]
].rename(columns={
    "start_station_id": "station_id",
    "start_station_name": "station_name"
})

end_stations = df_main[
    ["end_station_id", "end_station_name"]
].rename(columns={
    "end_station_id": "station_id",
    "end_station_name": "station_name"
})

# Combine both into one station reference table
stations = pd.concat(
    [start_stations, end_stations],
    ignore_index=True
).dropna().drop_duplicates()

# Count distinct names associated with each station ID
names_per_id = (
    stations.groupby("station_id")["station_name"]
    .nunique()
    .sort_values(ascending=False)
)

print("Unique station IDs:", stations["station_id"].nunique())
print("Unique station names:", stations["station_name"].nunique())

print(
    "Station IDs associated with multiple names:",
    (names_per_id > 1).sum()
)

display(names_per_id.head(10))

Unique station IDs: 2262
Unique station names: 2167
Station IDs associated with multiple names: 0

station_id
190 Morgan    1
2733.03       1
2782.02       1
2821.05       1
2832.03       1
2861.02       1
2872.02       1
2883.03       1
2898.01       1
2912.08       1
Name: station_name, dtype: int64

In [23]:
# Count unique station IDs associated with each station name
ids_per_name = (
    stations.groupby("station_name")["station_id"]
    .nunique()
    .sort_values(ascending=False)
)

print(
    "Station names associated with multiple IDs:",
    (ids_per_name > 1).sum()
)

print("\nMaximum IDs associated with one station name:")
print(ids_per_name.max())

print("\nExamples:")
display(ids_per_name[ids_per_name > 1].head(15))

Station names associated with multiple IDs: 95

Maximum IDs associated with one station name:
2

Examples:

station_name
Coffey St & Conover St         2
Central Ave & Decatur St       2
Amsterdam Ave & W 82 St        2
51 St & 43 Ave                 2
Brevoort Pl & Bedford Ave      2
Dawson St & Intervale Ave      2
E 138 St & Cypress Ave         2
Adams St & Prospect St         2
Congress St & Clinton St       2
E 34 St & Linden Blvd          2
31 Ave & Crescent St           2
Bergen St & Vanderbilt Ave     2
DeKalb Ave & S Portland Ave    2
36 St & Ditmars Blvd           2
79 St & 37 Ave                 2
Name: station_id, dtype: int64

In [24]:
# Select station names associated with multiple IDs
duplicate_names = ids_per_name[ids_per_name > 1].index

# Show the corresponding station IDs
station_id_pairs = (
    stations[
        stations["station_name"].isin(duplicate_names)
    ]
    .sort_values(["station_name", "station_id"])
)

display(station_id_pairs.head(30))

       station_id          station_name
4798       7386.1       2 Ave & E 99 St
66656     7386.10       2 Ave & E 99 St
6309       7152.1        24 Ave & 26 St
75119     7152.10        24 Ave & 26 St
912426     6960.1       3 Ave & E 71 St
971044    6960.10       3 Ave & E 71 St
906995     7154.1       3 Ave & E 81 St
972180    7154.10       3 Ave & E 81 St
13340      4110.1        3 St & Hoyt St
65536     4110.10        3 St & Hoyt St
1292       6893.1  31 Ave & Crescent St
73321     6893.10  31 Ave & Crescent St
74         6923.2   31 St & Newtown Ave
79528     6923.20   31 St & Newtown Ave
8209       6596.1        34 Ave & 45 St
68183     6596.10        34 Ave & 45 St
20207      7111.1  36 St & Ditmars Blvd
76096     7111.10  36 St & Ditmars Blvd
12565      6380.1        39 Ave & 99 St
113108    6380.10        39 Ave & 99 St
17582      6242.1        51 St & 43 Ave
65986     6242.10        51 St & 43 Ave
7490       6364.1       6 Ave & W 34 St
69312     6364.10       6 Ave & W 34 St
7548       5430.1     6 Ave & Walker St
75601     5430.10     6 Ave & Walker St
8          3834.1          6 St & 7 Ave
66999     3834.10          6 St & 7 Ave
1337       6365.1        79 St & 37 Ave
73325     6365.10        79 St & 37 Ave

In [25]:
# Check whether duplicate station IDs differ only by trailing zeros

station_id_pairs_check = station_id_pairs.copy()

station_id_pairs_check["normalized_id"] = (
    station_id_pairs_check["station_id"]
    .str.replace(r"(\.\d*?)0+$", r"\1", regex=True)
    .str.rstrip(".")
)

# Count distinct normalized IDs per station name
normalized_counts = (
    station_id_pairs_check.groupby("station_name")["normalized_id"]
    .nunique()
)

print("Names with equivalent IDs after normalization:")
print((normalized_counts == 1).sum())

print("\nNames still associated with different IDs:")
print((normalized_counts > 1).sum())

display(
    station_id_pairs_check[
        ["station_name", "station_id", "normalized_id"]
    ].head(20)
)

Names with equivalent IDs after normalization:
92

Names still associated with different IDs:
3

                station_name station_id normalized_id
4798         2 Ave & E 99 St     7386.1        7386.1
66656        2 Ave & E 99 St    7386.10        7386.1
6309          24 Ave & 26 St     7152.1        7152.1
75119         24 Ave & 26 St    7152.10        7152.1
912426       3 Ave & E 71 St     6960.1        6960.1
971044       3 Ave & E 71 St    6960.10        6960.1
906995       3 Ave & E 81 St     7154.1        7154.1
972180       3 Ave & E 81 St    7154.10        7154.1
13340         3 St & Hoyt St     4110.1        4110.1
65536         3 St & Hoyt St    4110.10        4110.1
1292    31 Ave & Crescent St     6893.1        6893.1
73321   31 Ave & Crescent St    6893.10        6893.1
74       31 St & Newtown Ave     6923.2        6923.2
79528    31 St & Newtown Ave    6923.20        6923.2
8209          34 Ave & 45 St     6596.1        6596.1
68183         34 Ave & 45 St    6596.10        6596.1
20207   36 St & Ditmars Blvd     7111.1        7111.1
76096   36 St & Ditmars Blvd    7111.10        7111.1
12565         39 Ave & 99 St     6380.1        6380.1
113108        39 Ave & 99 St    6380.10        6380.1

In [26]:
# Identify station names whose IDs remain different
unresolved_names = normalized_counts[
    normalized_counts > 1
].index

# Display their original and normalized IDs
unresolved_stations = station_id_pairs_check[
    station_id_pairs_check["station_name"].isin(unresolved_names)
].sort_values("station_name")

display(
    unresolved_stations[
        ["station_name", "station_id", "normalized_id"]
    ]
)

                       station_name station_id normalized_id
912460     Amsterdam Ave & W 119 St    7727.07       7727.07
6795       Amsterdam Ave & W 119 St    7727.08       7727.08
17716   DeKalb Ave & S Portland Ave    4546.04       4546.04
1263    DeKalb Ave & S Portland Ave    4546.06       4546.06
14730     Warren St & Roosevelt Ave    6346.02       6346.02
914283    Warren St & Roosevelt Ave    6346.07       6346.07

In [27]:
# Combine station IDs, names, and coordinates from both trip endpoints
start_locations = df_main[
    ["start_station_id", "start_station_name", "start_lat", "start_lng"]
].copy()

start_locations.columns = [
    "station_id", "station_name", "lat", "lng"
]

end_locations = df_main[
    ["end_station_id", "end_station_name", "end_lat", "end_lng"]
].copy()

end_locations.columns = [
    "station_id", "station_name", "lat", "lng"
]

all_locations = pd.concat(
    [start_locations, end_locations],
    ignore_index=True
)

# Focus on the three unresolved station names
unresolved_locations = all_locations[
    all_locations["station_name"].isin(unresolved_names)
]

# Calculate representative coordinates for each station ID
location_summary = (
    unresolved_locations
    .groupby(["station_name", "station_id"])
    .agg(
        median_lat=("lat", "median"),
        median_lng=("lng", "median"),
        observations=("lat", "count")
    )
    .reset_index()
)

display(location_summary)

,station_name,station_id,median_lat,median_lng,observations
0,Amsterdam Ave & W 119 St,7727.07,40.808625,-73.959621,1292
1,Amsterdam Ave & W 119 St,7727.08,40.808632,-73.959586,854
2,DeKalb Ave & S Portland Ave,4546.04,40.689810,-73.974931,153
3,DeKalb Ave & S Portland Ave,4546.06,40.689670,-73.975274,1989
4,Warren St & Roosevelt Ave,6346.02,40.749190,-73.870430,308
5,Warren St & Roosevelt Ave,6346.07,40.749190,-73.870540,143

In [28]:
# Count how often each ID appears as a start station
start_counts = (
    df_main[
        df_main["start_station_name"].isin(unresolved_names)
    ]
    .groupby(["start_station_name", "start_station_id"])
    .size()
    .rename("start_trips")
)

# Count how often each ID appears as an end station
end_counts = (
    df_main[
        df_main["end_station_name"].isin(unresolved_names)
    ]
    .groupby(["end_station_name", "end_station_id"])
    .size()
    .rename("end_trips")
)

# Standardize the index names so they can be combined
start_counts.index = start_counts.index.set_names(
    ["station_name", "station_id"]
)

end_counts.index = end_counts.index.set_names(
    ["station_name", "station_id"]
)

# Combine counts
station_usage = pd.concat(
    [start_counts, end_counts],
    axis=1
).fillna(0).astype(int)

station_usage["total_trips"] = (
    station_usage["start_trips"] + station_usage["end_trips"]
)

display(station_usage.reset_index())

                  station_name station_id  start_trips  end_trips  total_trips
0     Amsterdam Ave & W 119 St    7727.07          646        646         1292
1     Amsterdam Ave & W 119 St    7727.08          430        424          854
2  DeKalb Ave & S Portland Ave    4546.04           80         73          153
3  DeKalb Ave & S Portland Ave    4546.06          988       1001         1989
4    Warren St & Roosevelt Ave    6346.02          157        151          308
5    Warren St & Roosevelt Ave    6346.07           70         73          143

In [29]:
for column in ["start_station_name", "end_station_name"]:
    original = df_main[column]

    has_extra_spaces = (
        original.notna()
        & original.ne(original.str.strip())
    )

    print(column)
    print("Names with leading/trailing spaces:", has_extra_spaces.sum())
    print()

start_station_name
Names with leading/trailing spaces: 0

end_station_name
Names with leading/trailing spaces: 0

In [30]:
from pathlib import Path

processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

# Save the main analysis dataset
df_main.to_parquet(
    processed_folder / "citibike_2024_01_clean.parquet",
    index=False
)

# Save the 24+ hour trips separately
df_24h_plus.to_parquet(
    processed_folder / "citibike_2024_01_24h_plus.parquet",
    index=False
)

print("Both datasets saved successfully.")

Both datasets saved successfully.